---
- hosts: docker
  become: true
  vars:
    ansible_become_pass: edureka
  tasks:    
    - name: Install Docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io  

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes
        
